export const FETCH_TODO_LIST = "FETCH_TODO_LIST";
export const FETCH_TODO_UPDATE = "FETCH_TODO_UPDATE";
export const FETCH_TODO_ADD = "FETCH_TODO_ADD";
export const FETCH_TODO_DELETE = "FETCH_TODO_DELETE";
export const FETCH_TODO_ERROR = "FETCH_TODO_ERROR";
